engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: ".eslintrc.json"

  stylelint:
    enabled: true

ratings:
  paths:
    - "client/**/*"
    - "imports/**/*"
    - "server/**/*"
