bundle:
  build: ./app # EXPOSEs 80
  dockerfile: Dockerfile-bundle
  links:
    - db
    - proxy
  ports:
   - 8080:80
  environment:
   - ROOT_URL=https://local.cis-dev.brown.edu:3000
   - MONGO_URL=mongodb://db:27017/signmeup
   - VIRTUAL_HOST=local.cis-dev.brown.edu
   - METEOR_SETTINGS=${METEOR_SETTINGS}

db:
  image: mongo:latest # EXPOSEs 27017
  ports:
   - 27071:27071

proxy:
  image: jwilder/nginx-proxy:latest
  volumes:
   - ./nginx/ssl:/etc/nginx/certs
   - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
   - 80:80    # HTTP on 80
   - 3000:443 # HTTPS on 3000 to allow SAML to work
     