app:
  links:
   - db
   - proxy

db:
  image: mongo:latest # EXPOSEs 27017

proxy:
  image: jwilder/nginx-proxy:latest
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./nginx:/etc/nginx/certs
   - /var/run/docker.sock:/tmp/docker.sock:ro